Update Telegram bot workflow for notifications and tests

diff --git a/.github/workflows/telegram-bot.yml b/.github/workflows/telegram-bot.yml
--- a/.github/workflows/telegram-bot.yml
+++ b/.github/workflows/telegram-bot.yml
@@ -1,12 +1,77 @@
-name: Telegram Notification
-on: [push]
+on:
+  push:
+    branches:
+      - master
+  pull_request:
+    branches:
+      - "**"
 
 jobs:
-  notify:
+  docker:
+    timeout-minutes: 10
     runs-on: ubuntu-latest
+
     steps:
-      - name: Send Telegram Message
-        run: |
-          curl -s -X POST "https://api.telegram.org{{ secrets.TELEGRAM_TOKEN }}/sendMessage"\
-            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}"\
-            -d text="✅ GitHub 연결 성공!%0A작성자: ${{ github.actor }}%0A메시지: ${{ github.event.head_commit.message }}"
+      # 해당 저장소의 코드를 가져옵니다.
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      # Node 16 버전을 사용합니다.
+      - name: Install node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 18.x
+          cache: 'yarn'
+
+      # 설치된 yarn을 통해 패키지를 설치합니다.
+      - name: Install dependencies
+        run: yarn install
+
+      # 테스트 수행과 그 테스트 결과를 xml파일로 생성합니다.
+      - name: Run tests
+        run: yarn test:report
+
+      # 테스트 결과를 담은 xml 파일을 레포트로 변환합니다.
+      - name: Test Report
+        uses: dorny/test-reporter@v4
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: test-results
+          path: junit.xml
+          fail-on-error: 'false'
+          reporter: jest-junit        # Format of test results
+          token: ${{ secrets.GITHUB_TOKEN }}
+
+      # 빌드 성공 메세지 발송
+      - name: Send Build Success Message
+        uses: appleboy/telegram-action@master
+        if: success()
+        with:
+          to: ${{ secrets.TELEGRAM_CHAT_ID }}
+          token: ${{ secrets.TELEGRAM_TOKEN }}
+          format: markdown
+          message: |
+            Author: ${{github.actor}}
+            
+            Status: 😚 **Success**
+            
+            Commit message: ${{ github.event.commits[0].message }}
+            
+            [See changes](https://github.com/${{ github.repository }}/commit/${{github.sha}}) 
+
+      # 빌드 실패 메세지 발송
+      - name: Send Build Success Message
+        uses: appleboy/telegram-action@master
+        if: failure()
+        with:
+          to: ${{ secrets.TELEGRAM_CHAT_ID }}
+          token: ${{ secrets.TELEGRAM_TOKEN }}
+          format: markdown
+          message: |
+            Author: ${{github.actor}}
+            
+            Status: 😱 **Failure**
+            
+            Commit message: ${{ github.event.commits[0].message }}
+            
+            [link](https://github.com/${{ github.repository }}/actions)
